CREATE TABLE bachelor_ett_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid PRIMARY KEY NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);