CREATE TABLE bachelor_ett_contestants(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  contestant_id uuid NOT NULL PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  season INTEGER NOT NULL,
  date_created TIMESTAMP DEFAULT Now() NOT NULL
);