CREATE TABLE bachelor_ett_teams (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  team_id uuid PRIMARY KEY NOT NULL,
  team_name TEXT NOT NULL,
  user_id uuid REFERENCES bachelor_ett_users(user_id) NOT NULL,
  season INTEGER NOT NULL,
  date_created TIMESTAMP DEFAULT Now() NOT NULL
);